### ISSUE TITLE
CreateRequestSocket() CPU consumption

### ISSUE THREAD

**Issue by drew-r** [zeromq/netmq#208] opened 2015-01-21 13:34 UTC
Hi,
First off thanks for this project.
I am using the pre-release NuGet package 3.3.0.12-rc1 (.NET 3.5) and I am finding that a call to `CreateRequestSocket()` seems to result in unexpected CPU consumption.

When I exclude the following code block, the CPU usage returns to <2%. Otherwise it sits at 13% consistently.
```csharp
    ThreadPool.QueueUserWorkItem((o) =>
            {
                using (NetMQSocket request = _context.CreateRequestSocket()) // creating this socket seems to fix cpu consumption at 13%.. why?
                {
               
                }
            });
```

Is this a known phenomena?

TIA

**Comment by somdoron** [comment] 2015-01-21 17:14
@drew-r why did you close it? it is solved?

**Comment by drew-r** [comment] 2015-01-21 17:28
@somdoron No I have been trying to isolate the problem a bit better (hence edits).
It seems to occur on all socket types unless I wrap with `using (NetMQContext _context = NetMQContext.Create())` such that the context is disposed immediately after creation & usage.

**Comment by somdoron** [comment] 2015-01-21 17:30
Are you running on windows? Is it happening during the method call and then back to normal or still high all the time? Can you provide code to try and reproduce the issue?

**Comment by drew-r** [comment] 2015-01-21 17:32
Narrowed it down to .NET 3.5. Didn't occur under 4.5.
I've reproduced with the below:
```csharp
   class Program
    {
        static void Main(string[] args)
        {
            ThreadPool.QueueUserWorkItem((o) =>
            {
                using (NetMQContext context = NetMQContext.Create())
                {
                    using (NetMQSocket requester = context.CreatePushSocket()) // creating this socket seems to fix cpu consumptio at 13%.. why?
                    {
                        Console.WriteLine("LOADED");
                        Console.ReadKey();
                    }
                    Console.WriteLine("DISPOSED SOCKET");
                }
                Console.WriteLine("DISPOSED CONTEXT");
                Console.ReadKey();
            });


            while (true) Thread.Sleep(1000);
            
        }
    }
```

**Comment by somdoron** [comment] 2015-01-22 06:35
I think I know what is causing this. Because ConcurrectQueue doesn't exist in .net 3.5 I'm using a regular queue with locks to get safe queue. Probably causing the issue. I will try to fix that soon.

**Comment by somdoron** [comment] 2015-01-23 08:12
So the problem is that in dotnet 3.5 there is a bug with socket.select not blocking when called with -1.

**Comment by somdoron** [comment] 2015-01-23 08:30
@drew-r can you compile from https://github.com/somdoron/netmq/tree/dotNet35HighCPU and let me know it the issue is solved. Thanks

**Comment by drew-r** [comment] 2015-01-24 14:33
@somdoron this fixes. Nice work.

**Closed** 2015-01-25 13:33 UTC
