### ISSUE TITLE
NetMQ Server Crash when receiving message from Jeromq REQ socket

### ISSUE THREAD

**Issue by MarkOMeara123** [zeromq/netmq#693] opened 2017-08-18 06:35 UTC
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 10 64bit
    .NET Version:     4.6.1

### Expected behaviour
Expected NetMQ server to handle the request or Exception.

### Actual behaviour
NetMQ response socket faults in a way that stops the response socket from recieving any further requests until the application is restarted. There are no exceptions generated.

### Steps to reproduce the behaviour
Create a java client using Jeromq as per below. Configure a NetMQ Response socket to listen for messages.

In the ReceiveReady of the C# server the 'a.Socket.ReceiveFrameString();' crashes in a way that does not generate an exception - as it is not picked up by the try-catch. No further messages are recieved by the server until the server application is restarted.

The Java client and C# server are on the same Windows 1064bit machine.

//-----------------------------------------
// NETMQ Code C# Server
//-----------------------------------------
```

         static void Main(string[] args)
        {
            using (var server = new ResponseSocket())
            {
                server.Bind("tcp://*:6602");

                while (true)
                {
                    try
                    {
                        // Crashes here
                        var message = server.ReceiveFrameString();

                        Console.WriteLine("Received {0}", message);

                        // processing the request
                        System.Threading.Thread.Sleep(100);

                        Console.WriteLine("Sending World");
                        server.SendFrame("World");
                    }
                    catch (Exception ex)
                    {
                        // Does not exception!!!!!!!
                        Console.WriteLine(ex.ToString());
                    }
                }
            }
 }
```
//-----------------------------------------
//  JAVA CODE - CLIENT
//-----------------------------------------
```
import java.nio.charset.StandardCharsets;

import org.zeromq.ZMQ;

public class NetMQSimpleClient {
	 public static void main(String[] args) {
	        // Prints "Hello, World" to the terminal window.
	        //System.out.println("Hello, World");
	        
	        ZMQ.Context context = ZMQ.context(1);

	        //  Socket to talk to server
	        System.out.println("Connecting to hello world server");

	        ZMQ.Socket socket = context.socket(ZMQ.REQ);
	        socket.connect("tcp://127.0.0.1:6602");

	        for (int requestNbr = 0; requestNbr != 10; requestNbr++) {
	            String request = "Hello";
	            System.out.println("Sending Hello " + requestNbr);
	            byte[] b = request.getBytes(StandardCharsets.US_ASCII);
	            socket.send(b, 0);

	            byte[] reply = socket.recv(0);
	            System.out.println("Received " + new String(reply, ZMQ.CHARSET) + " " + requestNbr);
	        }

	        socket.close();
	        context.term();
	        
	    }
}
```

**Comment by somdoron** [comment] 2017-08-18 07:52
if you try ReceiveBytes instead of ReceiveString does it help?

do you get any message or nothing is passing between the applications?

**Comment by MarkOMeara123** [comment] 2017-08-18 12:06
Well technically there is no 'ReceiveBytes' or 'ReceiveString', it is 'ReceiveFrameBytes' and 'ReceiveFrameString' - perhaps I am using an old version of netmq? Anyway I have tried 'ReceiveFrameBytes' and also 'Receive(ref Msg)' and both also exhibit the same behaviour.

I am using the server poller method below for testing now as it permits me to put a breakpoint on the Receive method.

I know that the 'ReceiveFrameBytes' method  is executed as it hits a breakpoint set on that line. Delving deeper in the code a breakpoint in FairQueuring.cs line 112 ( `bool fetched = m_pipes[m_current].Read(ref msg);`) reveals that the message 'appears' to have been sent (I can see the ascii hello... or just 'ello', not certain). 
However the NetMQ code comes to a grinding halt in Signaler.cs line 117 (about the third poll). Here I see that `timeoutInMicroSeconds  ` has been set to  `Timeout.Infinite`, it enters the poll (`return m_readSocket.Poll(timeoutInMicroSeconds, SelectMode.SelectRead);`) and never returns from this.

So it seems that NetMQ is expecting more to be sent for some reason and sits there forever being somewhat annoying.

Any ideas?



C# Server Method
```
static void Main(string[] args)
        {
            using (var rep1 = new ResponseSocket("@tcp://*:6710"))
            using (var poller = new NetMQPoller { rep1 })
            {
                // these event will be raised by the Poller
                rep1.ReceiveReady += (s, a) =>
                {
                    // receive won't block as a message is ready
                    //Msg msg = new Msg();
                    //msg.InitEmpty();
                    var msg = a.Socket.ReceiveFrameBytes();
                    // send a response
                    a.Socket.SendFrame("Response");
                };
               
                // start polling (on this thread)
                poller.Run();

                Console.ReadLine();
            }
        }
```

**Comment by somdoron** [comment] 2017-08-18 13:45
Ok, might be that Request & Reponse socket are implemented differently between NetMQ and JeroMQ.

I suggest using Dealer & Router instead.

**Comment by MarkOMeara123** [comment] 2017-08-18 21:32
Same issue with Dealer/Router. One of the beneifit of using zeromq was interoperability between different programming langauges. Very dissapointing.

**Comment by MarkOMeara123** [comment] 2017-08-18 21:53
I can confirm that ZeroMQ C# from nuget works just fine with the java client. You have something non standard going on in NetMQ.

```
using (var context = new ZContext())
            using (var responder = new ZSocket(context, ZSocketType.REP))
            {
                // Bind
                responder.Bind("tcp://*:6710");

                while (true)
                {
                    // Receive
                    using (ZFrame request = responder.ReceiveFrame())
                    {
                        Console.WriteLine("Received {0}", request.ReadString());

                        // Do some work
                        Thread.Sleep(1);

                        // Send
                        responder.Send(new ZFrame("Ok"));
                    }
                }
            }
```

**Comment by somdoron** [comment] 2017-08-19 13:16
well netmq talks to zeromq in production very nicely, so that is not the issue.

I suspect that the new version of jeromq might not support ZMTP v2 which NetMQ is using. JeroMQ recently upgrade to ZMTP v3, so it might be JeroMQ not support ZMTP v2 or the downgrade to ZMTP v2 is not working correctly.

I suggest trying with older versions of JeroMQ in order to rule out downgrade problem.

@trevorbernard does JeroMQ supporting downgrading to ZMTPv2?

**Comment by somdoron** [comment] 2017-08-19 13:20
from looking at the code it seems JeroMQ does support ZMTP v2, the only question is does the downgrade for v2 has been tested. I suggest you try JeroMQ with libzmq v3 and older JeroMQ versions (that don't implement ZMTP v3) with NetMQ.

**Comment by MarkOMeara123** [comment] 2017-08-19 20:44
ok. Unfortunately ZermoMQ c# nuget has no history so I cannot downgrade that to test against v3. However I have downgraded JeroMq and tested against NetMQ. I can confirm communication between the two was broken in jeromq v0.4.1 and v0.4.2, prior versions including v0.4.0 work fine with NetMQ.
Great news. Thanks.

Now however I am worried my NetMQ server may get stuck in an infinite poll should there be a comms issue at some point. Do you have suggestions for detecting the issue?

**Comment by somdoron** [comment] 2017-08-20 07:55
Great. If you are opening an issue on jeromq please send a link. I will try to help.

**Comment by bblazei** [comment] 2017-09-05 19:44
also hit this issue with Pub/Sub from JeroMQ v0.4.2
downgrade to JeroMQ v0.4.0 'solved' the issue

curiously, messages from JeroMQ v0.4.2 were processed as expected in my c++ client with libzmq 4.2.0. makes me think this issue isn't with JeroMQ after all.

anyway, thank you Mark for discovering this fix

**Comment by trevorbernard** [comment] 2017-09-06 03:50
Sounds like it's an issue with JeroMQ. https://github.com/zeromq/jeromq/pull/461 involved a problem with handshaking. @bblazei Can you verify this is still a problem with the latest jeromq master?

**Comment by somdoron** [comment] 2017-09-06 05:56
@bblazei NetMQ is using ZMTP v2 (wire procotol) and ZeroMQ and JeroMQ both are using ZMTP v3.0 with downgrade comparability. So when JeroMQ talks to ZeroMQ  they use ZMTP v3.0. When JeroMQ talks to NetMQ, JeroMQ need to downgrade to v2. There was a bug with JeroMQ downgrading to v2, which is now fixed.

**Closed by somdoron** 2017-09-06 05:56 UTC

**Comment by bblazei** [comment] 2017-09-06 18:43
@trevorbernard confirmed that latest master code does not exhibit this problem :smiley: i'm able to pub/sub successfully! btw not sure if by design, but i couldn't find 0.4.3-SNAPSHOT in the public nexus so had to checkout and install locally

+ @somdoron thanks for the speedy replies guys

**Comment by goldinof** [comment] 2017-12-03 23:15
I have this issue connecting two apps using both NetMQ

**Comment by jasells** [comment] 2019-10-07 20:10
Has anyone tried this scenario in reverse?  a JeroMQ server with NetMQ client???

I am trying this scenario with a JeroMQ PUB and NetMQ SUB, and the NetMQ client never sees *any* topics from TryReceive, nor does ReceiveReady ever fire.  

I  re-ran the test scenario with the ZeroMQ C# wrapper package, and it works with the same JeroMQ PUB socket.
