### ISSUE TITLE
Unable to subscribe from third party app from netmq but works fine in pyzmq

### ISSUE THREAD

**Issue by gullyy** [zeromq/netmq#498] opened 2016-03-02 05:30 UTC
I have a third party app which publishes(I have no control on the publish). When the subscriber is using python code -using pyzmq it is able to subscribe, however when I subscribe using c#-netmq there is no subscription. The subscriber is not being hit at all.Where am I going wrong?

Python code

 import sys
 import zmq
 context=zmq.Context()
 socket=context.socket(zmq.SUB)
 print "Collecting updates from "
 socket.setsockopt(zmq.SUBSCRIBE, '')
 socket.connect("tcp://127.0.0.1:2027")
 while True:
 string=socket.recv()
 print string
 C# CODE

        public static void sub()
       {

        using (var context = NetMQContext.Create())
        {
            using (var subscriber = context.CreateSubscriberSocket())
            {
               // subscriber.Options.ReceiveHighWatermark = 1000;
                subscriber.Connect("tcp://localhost:2027");
                // subSocket.Subscribe(topic);
                Console.WriteLine("Subscriber socket connecting...");
                while (true)
                {
                    string messageTopicReceived = subscriber.ReceiveFrameString();
                    string messageReceived = subscriber.ReceiveFrameString();
                    Console.WriteLine(messageReceived);
                }
            }
        }
    }

**Comment by somdoron** [comment] 2016-03-02 08:16
try to subscribe to all topics with

subSocket.Subscribe("");

**Comment by gullyy** [comment] 2016-03-02 12:16
@somdoron tried but nope it doesnt work.I am using zmq 2.2.0 stable release in case that information matters.

**Comment by somdoron** [comment] 2016-03-02 12:23
So yes, NetMQ currently have a bug and cannot connect to zmq v2.2

I will try to fix it today

**Comment by gullyy** [comment] 2016-03-02 12:35
Thanks a lot @somdoron

**Comment by somdoron** [comment] 2016-03-02 12:44
can you build from following and check if the problem is fixed?

https://github.com/somdoron/NetMQ3-x/tree/zmqv2fix

**Comment by somdoron** [comment] 2016-03-02 12:45
if not, can you provide me with a zmq v2.2 exe file or even a endpoint I can check with?

**Comment by gullyy** [comment] 2016-03-02 13:00
https://miru.hk/archive/ZeroMQ-2.2.0~miru1.0-win32.exe
This is the zmq exe.
Pretty new to .net so will try to build from the above link

**Comment by gullyy** [comment] 2016-03-02 13:49
So here is what I did.I cloned the project opened the sln file (in visual studio) did a build.Then copied the NetMQ.dll from 'Debug' folder to 'packages\NetMQ.3.3.2.2\lib\net40' folder in my project.
It didnot work.Hope this is the right way to do it.

**Comment by somdoron** [comment] 2016-03-03 15:54
So I tested it too, seems to solve the issue.

Regarding how to use it, I will release new RC version when pull requests are merged.

**Closed** 2016-03-03 17:59 UTC
