### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by matthiasgeller** [zeromq/netmq#99] opened 2013-09-23 13:49 UTC
U are using ReSharper... So maybe u could refactor some classes and extract some interfaces to be able to simplify writing unit tests using a mocking framework instead of always writing integration tests.

Really cool would be all classes which are using private constructors only (like the NetMQContext class).

Temporarily i am using adapters realizing fake interfaces to solve that problem... But please...

Thx & Greetz
Matthias Geller

**Comment by drewnoakes** [comment] 2015-03-08 19:15
I figure this is a duplicate of #63 so will close it.

**Closed by drewnoakes** 2015-03-08 19:15 UTC
