### ISSUE TITLE
nuget release

### ISSUE THREAD

**Issue by somdoron** [zeromq/netmq#315] opened 2015-03-25 14:12 UTC
What do you think should be our nuget release process? Here are some of my ideas:

Idea #1
* Beta version - continues from the source and build (or minor?) part of the version is odd and revision is continues number + the beta to make it pre-release or we can also have a different nuget project for this entirely to make sure nobody confuse (still with odd versioning).
* Stable version - build number is even, manual process of picking fixes to a special repository. When do we decide on a new stable version?

Idea #2 
Release candidate repository which we cherry-pick fixes from master, when ever the beta release candidate seems stable we upgrade it to stable and promote the current master to release candidate (and increase the minor). We can use the NetMQ organization for the repositories.

What do you think?

**Comment by drewnoakes** [comment] 2015-06-03 13:56
Can this be closed as a dupe of #342?

**Closed** 2015-06-09 08:31 UTC
