### ISSUE TITLE
Proxy with no traffic still consumes over 20% cpu

### ISSUE THREAD

**Issue by robvon** [zeromq/netmq#797] opened 2019-06-18 01:34 UTC
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: WIndows Server 2012
    .NET Version:     4.7.2

### Expected behaviour

More or less no CPU overhead except when processing messages. BTW, the proxy works just fine when it does receive a message.

### Actual behaviour

Between 10 and 40% of the server is being consumed

**Comment by drewnoakes** [comment] 2019-06-18 04:53
Duplicate of #798

**Closed by drewnoakes** 2019-06-18 04:53 UTC
