### ISSUE TITLE
NetMQ.NetMQException on long running application

### ISSUE THREAD

**Issue by azafeh** [zeromq/netmq#633] opened 2016-12-26 21:25 UTC
### Environment

    NetMQ Version:     NetMQ 4.0.0-rc5 
    Operating System:  Windows Server 2012
    .NET Version:     4.6.1

Hello, 

After a day or so the application is open the following exception is raised when it tries to create a new PairSocket:

    NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown.
      at NetMQ.Core.Ctx.CreateSocket(ZmqSocketType type)
      at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
      at NetMQ.Sockets.PairSocket.CreateSocketPair(PairSocket& socket1, PairSocket& socket2)
      at NetMQ.Core.Utils.StopSignaler..ctor()
      at NetMQ.NetMQPoller..ctor()

If I close and reopen the application, all works again. The total number of connections is pretty low (barely a few hundred). Is there any caveat/limitation with PairSockets? Any ideas about what might be happening?

**Comment by Giles-S** [comment] 2017-02-08 12:13
I'm also experiencing this issue. Did you manage to find the cause? Thanks.

**Comment by drewnoakes** [comment] 2017-02-08 13:10
Do you have more information about the exception? Perhaps there is an inner exception.

**Comment by Giles-S** [comment] 2017-02-08 15:38
Hi. Thanks for replying. There wasn't an inner exception, which was one of the things stumping me. I have since noticed an error code though - NetMQ.ErrorCode.EMFILE. which from the documentation I've found seems to have been superseded by another error "TooManyOpenSockets", so I presume that's the issue. I'm not sure if my approach is correct, but I'm creating a RequestSocket for each call I make, and am subsequently calling Disconnect. As per the OP, I only get the exception when the application has been running a while. I've just noticed that I'm not explicitly calling Dispose though, so suspect some resource may be getting exhausted before garbage collection runs. I'll try that and leave it running a while.

**Comment by drewnoakes** [comment] 2017-02-08 21:55
It does sound like you're running out of sockets. There should be tools to detect this (depending on your OS).

Can't you keep the socket and reuse it?

Regardless, if you're not using the socket any more, dispose it.

**Comment by drewnoakes** [comment] 2017-02-08 22:41
On Windows you can use the amazing [Process Hacker](https://github.com/processhacker2/processhacker2) to see port consumption. Check the 'network' tab on the main window.

**Comment by Giles-S** [comment] 2017-02-09 09:24
Thanks for your help and the recommendations Drew - Process Hacker sounds useful. Calling Dispose appears to have solved the problem. A little digging revealed that Dispose calls Close, whereas I was only explicitly calling Disconnect.

**Comment by drewnoakes** [comment] 2017-05-01 08:44
Sounds like you got this sorted, so closing for now.

**Closed by drewnoakes** 2017-05-01 08:44 UTC
