### ISSUE TITLE
NetMQPoller prevents AppDomain unload when not disposed

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#516] opened 2016-03-21 11:30 UTC
This happens even if I add the following:

```
~NetMQPoller()
        {
            Dispose();
        }
```

Only explicit dispose stops my unit tests. Calling poller.Stop() without disposing sometimes leads to an error on the subsequent test run with a message about port being already used. I would expect a finalizer with `GC.SuppressFinalize(this);` on the last line of `Dispose()` method work properly.

**Comment by somdoron** [comment] 2016-03-21 13:10
Can you make a PR?

**Comment by buybackoff** [comment] 2016-03-21 13:13
I haven't figured out how to change the code. The finalizer doesn't help, which could mean it is not called at all and there is some hidden reference to a poller that is released when a poller is disposed.

**Comment by Green7** [comment] 2016-03-24 19:52
I have this same problem (in 4.0.0-beta)
I think that the problem is caused by not stopped NETMQ threads.
For example: thread started in Proactor.Start() still working even if we call Proactor.Dispose
(and NetMQPoller internally uses Proactor).

How to reproduce error:
- create MS unit test (not Nunit) and debug this code:
```
	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void PoolerTest()
		{
			using (var poller = new NetMQPoller())
			{
				poller.RunAsync();
				poller.Stop();
				
			}
		}
	}

```

The execution will take a long time and in ouput/debug window you will se exceptions. Here is exception stack:

> System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Nieobsługiwany wyjątek</Description><AppDomain>vstest.executionengine.x86.exe</AppDomain><Exception><ExceptionType>System.Threading.ThreadAbortException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Trwało przerywanie wątku.</Message><StackTrace>   w System.Net.UnsafeNclNativeMethods.OSSOCK.select(Int32 ignoredParameter, IntPtr[] readfds, IntPtr[] writefds, IntPtr[] exceptfds, IntPtr nullTimeout)
>    w System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
>    w NetMQ.Core.Utils.SocketUtility.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
>    w NetMQ.Core.Utils.Poller.Loop()
>    w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    w System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.Threading.ThreadAbortException: Trwało przerywanie wątku.
>    w System.Net.UnsafeNclNativeMethods.OSSOCK.select(Int32 ignoredParameter, IntPtr[] readfds, IntPtr[] writefds, IntPtr[] exceptfds, IntPtr nullTimeout)
>    w System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
>    w NetMQ.Core.Utils.SocketUtility.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
>    w NetMQ.Core.Utils.Poller.Loop()
>    w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    w System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>

I want to fix this but I can't find good method to stop Pooler thread.

**Comment by somdoron** [comment] 2016-03-30 13:19
So why not to just dispose the poller?

**Comment by somdoron** [comment] 2016-03-30 13:25
The thing, it can be fixed, but it a little complicated.

**Comment by Green7** [comment] 2016-03-30 14:01
If you dispose the poller thread created by pooler still working. 
Yes I agree is complicated to fix but without this fix unit testing is hard.

**Comment by somdoron** [comment] 2016-03-30 14:21
If you dispose the poller thread is also killed (if used RunAsync).

The proactor thread is internal for NetMQ io, it will be killed once the application has exit.

**Comment by Green7** [comment] 2016-04-08 13:35
Yes you are right - all internal threads are finished when application finish.
But this approach not works in unit testing. 
In unit testing the test executor waits for the completion of all threads and AFTER this it finishes application. 
I have the same problem in C/C++ version of zeromq. But in C I have function zsys_shutdown() which  terminates all internal threads. So I can call  zsys_shutdown()  on test cleanup and test is finished properly. 
NetMQ should have similar function and I think that it is easy to implement in NetMQConfig class.

**Comment by somdoron** [comment] 2016-04-08 15:41
Sounds good, want to make a pull request?

**Comment by Green7** [comment] 2016-04-08 16:13
I try :)

**Comment by CodyBatt** [comment] 2016-05-04 00:57
I have the same issue with unit tests, any progress on this?

**Comment by somdoron** [comment] 2016-05-05 13:16
yes, NetMQ now support manual termination. So at the end of the app domain call 

```C#
NetMQConfig.ManualTerminationTakeOver();
NetMQConfig.ContextTerminate();
```

Compile from source.

**Comment by ondrejtomcik** [comment] 2016-06-01 11:09
Is there any solution for actual stable release 3.x ?

**Comment by somdoron** [comment] 2016-07-01 15:14
@ondrejtomcik are you using NetMQContext or not? If not I can port the Manual termination fix to version 3

**Comment by samcragg** [comment] 2016-07-07 05:49
I have the same issue creating sockets in a unit test (via NUnit) - because I can't mock the NetMQSocket I'm having to create a real one but then the unit tests would hang. I've worked around it by using [NUnit.ApplicationDomain](https://www.nuget.org/packages/NUnit.ApplicationDomain), but it would be great if the changes to NetMQConfig could be pushed to the NuGet package (I tried the pre-release but they still weren't there).

Anyway, here's how I got the unit tests working, hope it helps:

    using System;
    using System.Text;
    using NetMQ;
    using NetMQ.Sockets;
    using NUnit.Framework;

    [TestFixture]
    public sealed class PollingSocketTests
    {
        private NetMQSocket local;
        private NetMQSocket remote;

        [SetUp]
        public void SetUp()
        {
            if (AppDomainRunner.IsInTestAppDomain)
            {
                string address = "inproc://polling_test_" + Guid.NewGuid();
                this.local = new PairSocket("@" + address);
                this.remote = new PairSocket(">" + address);
            }
        }

        [TearDown]
        public void TearDown()
        {
            if (AppDomainRunner.IsInTestAppDomain)
            {
                this.local.Dispose();
                this.remote.Dispose();
            }
        }

        [Test]
        [RunInApplicationDomain]
        public void CanSendAMessage()
        {
            byte[] data = Encoding.UTF8.GetBytes("Hello");

            Msg msg = new Msg();
            msg.InitGC(data, data.Length);
            this.local.TrySend(ref msg, TimeSpan.Zero, false);

            this.remote.TryReceive(ref msg, TimeSpan.Zero);
            string text = Encoding.UTF8.GetString(msg.CloneData());
            msg.Close();

            Assert.That(text, Is.EqualTo("Hello"));
        }
    }

**Comment by somdoron** [comment] 2016-07-09 17:59
take a look at the following PR:

https://github.com/zeromq/netmq/pull/576

you can now cleanup the library with

NetMQConfig.Cleanup();

If you don't want the process to block you can also call

NetMQConfig.Cleanup(false);

**Comment by samcragg** [comment] 2016-07-10 20:55
That sounds great, thanks for adding that!

I noticed the NuGet package was updated on the same day as the commit (version [3.3.3.3](https://www.nuget.org/packages/NetMQ/3.3.3.3)) however, I can't see the new method in there (I've even downloaded it from the website and took a look at the DLL in the decompiler but `NetMQ.NetMQConfig.Cleanup()` doesn't exist) - do I have to compile it from source to get the new method?

**Comment by somdoron** [comment] 2016-07-10 21:12
Yes,  not yet on nuget.  Probably  by the end of the week

**Comment by somdoron** [comment] 2016-07-13 17:44
@samcragg it is on nuget now, on both NetMQ v4 and NetMQ v3:
https://www.nuget.org/packages/NetMQ/3.3.3.4
https://www.nuget.org/packages/NetMQ/4.0.0.1-rc1

**Comment by somdoron** [comment] 2016-07-13 17:47
@buybackoff can we close this?
I think you have a solution now, first I suggest disposing NetMQPoller correctly. 
You can now call NetMQConfig.Cleanup(false) after each test.

You can read more here:
http://netmq.readthedocs.io/en/latest/cleanup/

**Comment by buybackoff** [comment] 2016-07-13 17:53
Sounds good. Please close if this is solved for all other reported cases as well.

**Closed** 2016-07-13 18:02 UTC

**Comment by Rajnkr** [comment] 2018-06-21 07:57
Thanks for the fix, The above discussion helped us to solve the issue in very short time frame.
Great Team work !

Thanks Once again!
